# Generated by Django 4.2.17 on 2025-01-02 20:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=250, null=True)),
                ('adres', models.CharField(blank=True, max_length=255, null=True)),
                ('pro_picture', models.ImageField(blank=True, null=True, upload_to='media/users/')),
                ('phone_number', models.CharField(blank=True, max_length=25, null=True)),
                ('mobile_number', models.CharField(blank=True, max_length=25, null=True)),
                ('web_url', models.CharField(blank=True, max_length=50, null=True)),
                ('github_url', models.CharField(blank=True, max_length=50, null=True)),
                ('twitter_url', models.CharField(blank=True, max_length=50, null=True)),
                ('insta_url', models.CharField(blank=True, max_length=50, null=True)),
                ('facebook_url', models.CharField(blank=True, max_length=50, null=True)),
                ('followers', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='followed_profiles', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user profile')),
            ],
        ),
        migrations.CreateModel(
            name='UserFollowersModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('follower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
